### PR TITLE
Multi fed and cleanup

### PR DESCRIPTION
**Pull request by okjodom**
here are some changed I think we can add to https://github.com/fedimint/ui/pull/367

- enables reuse of input box to connect multiple feds
- shows information of all connected feds as cascading cards. The benefit of this UX is that you can take actions across multiple feds in a single sweep, like copying deposit address from one fed card and pasting in another fed card as withdraw destination?
- bunch of cleanups in gateway code

[Screencast from 2024-02-07 09:52:04 AM.webm](https://github.com/Kodylow/fedimint-ui/assets/11217077/c972a251-5fab-4cd1-83a1-bc5384122b95)

### CODE REVIEW

**Comment by Kodylow** [comment]
We should have the "join another federation" be a modal or something instead of just sitting there taking up space. Or move it to the bottom?

having all of them viewable and scrollable seems functional if not the most design-y haha, I like it, maybe we change the layout a little to make them more clearly per federation and just have "Lightning Dashboard" at the top

**Comment by okjodom** [comment]
> We should have the "join another federation" be a modal or something instead of just sitting there taking up space. Or move it to the bottom?
> 
> having all of them viewable and scrollable seems functional if not the most design-y haha, I like it, maybe we change the layout a little to make them more clearly per federation and just have "Lightning Dashboard" at the top

Makes sense to have the connect-fed input collapsible and controlled by a button? Original UI sketch had something like that.

**Comment by Kodylow** [comment]
Yeah I think putting it in the top right , Lightning Gateway Dashboard in top left, then all connected fed underneath would be good.

**Comment by okjodom** [comment]
> Yeah I think putting it in the top right , Lightning Gateway Dashboard in top left, then all connected fed underneath would be good.

which one looks neater? The button in top right, in-lined with the outer most header which contains FM logo
image

or top right, inlined with the "Lightning Gateway Dashboard" header text
image

Difference is on the last two commits

**Comment by Kodylow** [comment]
It shouldn't show the top right button if the connect federation stuff is opened, otherwise it's good, maybe switch it to an X?

**Comment by okjodom** [comment]
> It shouldn't show the top right button if the connect federation stuff is opened, otherwise it's good, maybe switch it to an X?
> 

maybe X with additional text like 'Cancel' or 'Close', so its not a drastic UI change.

**Comment by Kodylow** [comment]
yeah that dounds good

**Pull request merged**
